apiVersion: cloudflare.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: cloudflare-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: cloudflare-provider
      namespace: crossplane-system
      key: credentials
